### ISSUE TITLE
Cannot find the add-on in the add-on store

### ISSUE THREAD

**Issue by LinqLover** [hassio-addons/addon-vscode-remote#122]
# Problem/Motivation

Trying to follow the [installation instructions](https://github.com/hassio-addons/addon-vscode-remote/blob/main/vscode-remote/DOCS.md#installation) which say:

> Search for the "VSCode Remote" add-on in the Supervisor add-on store and install it.

## Expected behavior

So I go to <https://my.home-assistant.io/redirect/supervisor_store/> and type in "VSCode Remote" ...

## Actual behavior

... but unfortunately, there are no results:

> No results found in Official add-ons.
> 
> No results found in ESPHome.
> 
> No results found in Home Assistant Community Add-ons.

## Steps to reproduce

(see above)

## Proposed changes

It would be great if you could clarify the installations and/or the requirements for installing this add-on.

My system is:

> Home Assistant 2022.9.6
> Supervisor 2022.09.1
> Operating System 9.0
> Frontend 20220907.2 - latest

**Comment by frenck** [comment]
That is correct, this add-on hasn't been released.

https://github.com/hassio-addons/addon-vscode-remote/releases
