### ISSUE TITLE
Is this add on abandoned?

### ISSUE THREAD

**Issue by mietzen** [hassio-addons/addon-vscode-remote#146]
I got the same Issue as already reported and staled/closed in #59.
I guess password auth never worked since it is disabled, even if a password is provided:
`PasswordAuthentication no`

@frenck Is this add on abandoned? Then please archive this repo.

**Comment by frenck** [comment]
This add-on has never been released.

> Then please archive this repo.

Why?

**Comment by mietzen** [comment]
> This add-on has never been released.
> 
> > Then please archive this repo.
> 
> Why?

Because your last commit is a year old and issues like #59 are left unanswered and are closed automatically. 
So released or not in my view this add on is without some who wants to develop it and make it functional. Hence archive it, if some one wants to pickup your work they can still fork it. For everybody else there is a clear indicator that no one is working on this.

**Comment by frenck** [comment]
ok thanks for your suggestion.

**Comment by mietzen** [comment]
> @frenck Is this add on abandoned? Then please archive this repo.

ok thanks for only indirectly answering my question.
